services:
  flare-mainnet:
    restart: always
    # image: flarefoundation/go-flare:v1.7.1807
    pull_policy: always
    image: thedavidmeister/go-flare
    logging:
      driver: local
    environment:
      - NETWORK_ID=flare
      - AUTOCONFIGURE_BOOTSTRAP=1
      - AUTOCONFIGURE_BOOTSTRAP_ENDPOINT=https://flare.flare.network/ext/info
    volumes:
      - "flare-db:/app/db"
      - "flare-logs:/app/logs"
      - "flare-conf:/app/conf"
    ports:
      # external/public port for basic HTTP is 9650 by default
      # exposed locally for use by bot on same machine
      - "0.0.0.0::9650"
    profiles: ["flare", "flare-node"]

  flare-bot:
    restart: always
    image: rainprotocol/arb-bot:dog-wire
    pull_policy: always
    logging:
      driver: local
    environment:
      - RPC_URL=${RPC_URL:-http://flare-mainnet:9650/ext/bc/C/rpc}
      - BOT_WALLET_PRIVATEKEY=${BOT_WALLET_PRIVATEKEY}
      - ARB_ADDRESS=${ARB_ADDRESS}
      - GENERIC_ARB_ADDRESS=${GENERIC_ARB_ADDRESS:-}
      - SUBGRAPH=${SUBGRAPH}
      # Default to 0 because the default is hitting a local RPC.
      - SLEEP=${SLEEP:-0}
      - HYPERDX_API_KEY=${HYPERDX_API_KEY:-}
      - TRACER_SERVICE_NAME=${TRACER_SERVICE_NAME:-}
      - MAX_RATIO=true
      - HOPS=${BINARY_SEARCH_HOPS:-1}
      - BOT_MIN_BALANCE=${BOT_MIN_BALANCE}
    profiles: ["flare", "flare-bot"]

volumes:
  flare-db:
    external: true
  flare-logs:
    external: true
  flare-conf:
    external: true
